### ISSUE TITLE
Error when bundling with browserify

### ISSUE THREAD

**Issue by in1gotech-jdjaviniar** [lobodpav/node-app-config#1]
Hi!

I tried to create a **bundle *\* using `browserify`including the app-config module in my **web-application**,
but I received the following error:

```
Uncaught TypeError:fs.existsSync is not a function
    (anonymous function) @ index.js:441
     require.5._process    @ index.js:503
     s                                @ index.js:1
    ....
```

It is pointing to a function call fs.existsSync(), in this code:

```
...
// check for non-existence of configuration directory

if (!fs.existsSync(CONFIG_DIR)) { // <<-- app errored in this part ...

    if (LOG || HALT) // always print the error if halting the app
        console.error('Configuration directory for the app is missing. Expected location is', CONFIG_DIR);
    if (HALT) {
        console.error('Halting the app.');
        process.exit(-1);
    } else {
        module.exports = null;
        return;
    }
}
...
```

I am using:

node :  v4.1.1
app-config : v0.1.5
browserify : v13.0.0

**Comment by lobodpav** [comment]
Hello! I have neither tried nor tested the `app-config` module in browser.
However, from the message you got it seems that the [File System](https://nodejs.org/dist/latest-v4.x/docs/api/fs.html#fs_fs_existssync_path) NodeJS module does not have the `existSync()` function available.

Is it even possible for any browser to access directories with configuration files on a physical hard drive?
